### ISSUE TITLE
ASN1 structure usage and AccessViolationException in MSVC

### ISSUE THREAD

**Issue by khevessy** [riebl/vanetza#172] opened 2022-10-21 12:09 UTC
Hi all,

I've managed to compile Vanetza in a C++/CLI environment and want to use it as a DLL library under C#.
I am trying to use ASN.1 structures. It doesn't matter if I use the `cpp` wrapper classes or not.

It is enough if I use this line: 
```
vanetza::asn1::Cam message;
```
and program fails with this error
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at <Module>.vanetza.asn1.free(asn_TYPE_descriptor_s*, Void*)
--------------------------------
   at NativeCodeWrapper..ctor()
   at Example.Main()
```
I also tried 
```
CAM_t* cam = vanetza::asn1::allocate<CAM_t>();
// Fill in the structure
vanetza::asn1::free(asn_DEF_CAM, cam);
```
and it fails with the same error. It is apparent that it is caused by trying to free the structure. The address seems correct to me (usually something around 0x00000267B4216AD0).
Does anyone have an idea what could be causing this?

Regards,
Karel

**Comment by riebl** [comment] 2022-10-23 19:38
Though asn1c is far from perfect, I don't think it's the culprit this time. I have just run extensive memory checks with Valgrind on the `GTest_ItsAsn1` unit test target without any findings. Thus, I suppose the issue may be caused by some build configuration for MSVC, e.g. some preprocessor statements testing for MSVC or Win32 and thus adapting the source code. This would at least explain why no memory error is detected on my Linux build.

**Comment by Irisbus** [comment] 2022-10-25 07:36
Some other notes:
- Same exception occurs if the CAM message is created in a module that was built without CLR support
- Size of the allocated strructure is correct (same as in Linux)

**Comment by Irisbus** [comment] 2022-10-25 13:40
Unfortunately I am not able to debug the project properly as the DEBUG configuration is for some reason not working for now,

**Comment by riebl** [comment] 2022-10-26 15:45
Phew, I have never entered the dungeons of DLL symbols. If that is really the causing issue, then an *AccessViolationException* is not exactly pinpointing in that direction. At least not my first guess ;-)

**Comment by riebl** [comment] 2022-10-26 16:03
In the end, I would love to have Windows/MSVC as another target included in our GitHub actions executed for every commit. A few years ago I built Vanetza on Windows out of curiosity but not with MSVC. I had no use case for this, though.

**Comment by Irisbus** [comment] 2022-10-31 09:20
I think that with DLLs, ASN1 structures cannot be initialized the way they are now. Problem is that it is impossible to use address of `dllimport`ed symbol in an initializer.
I managed to encode the CAM messages and also use your wrapper class without crash. My solution is to add a `C` file to each asn1 project (asn1_its, asn1_pki, asn1_security) and in that file, manually include the `C` file with definition of the needed symbols (`constr_SEQUENCE.c`, `NativeInteger.c` and so on). That way, each DLL has its own copy that it uses. But this probably is not something you would want in your codebase.

**Comment by Irisbus** [comment] 2022-10-31 09:23
> In the end, I would love to have Windows/MSVC as another target included in our GitHub actions executed for every commit. A few years ago I built Vanetza on Windows out of curiosity but not with MSVC. I had no use case for this, though.

But you built it as a static library, no? I think this could be added to the actions as you are saying. I do not know how to do that though.

**Comment by riebl** [comment] 2022-11-03 18:37
> But you built it as a static library, no? I think this could be added to the actions as you are saying. I do not know how to do that though.

Yes, I think so, but I don't remember the details anymore. Building static libraries should work for C++/CLI as well, shouldn't it?

**Comment by Irisbus** [comment] 2022-11-04 08:19
Yes, static libraries work fine.

As for the DLLs, there is one more problem - I had to use define CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS so that all the Vanetza functions are exported (windows does not do this automatically, everywhere would have to be the `__declspec(dllexport)` directive). But there is a [known bug](https://gitlab.kitware.com/cmake/cmake/-/issues/23116) that there are exported some standard library symbols that shouldn't be and the linking then fails. One solution is to comment out the offending definitions in the resulting `.def` export file, other solution is to use the `/FORCE` directive for the linker so that it ignores multiply defined symbols. This works for me, however it is not the most clean solution.

If you wanted, I can write instructions with all the steps needed to do the build under MSVC as there were few more workarounds I had to do. Dirtiest was adding a dummy member to empty unions in `vanetza/asn1/its/RegionalExtension.h`, as it seems that standard C does not allow this but it is ignored by gcc (MSVC `error C2016: C requires that a struct or union has at least one member`).

I think I can close this issue now as everything seems to work now (with the structures put in the `.c` files as mentioned in my previous comment). Should I create another issue with adding static library build to the GitHub actions as you mentioned?

**Comment by riebl** [comment] 2022-11-05 19:59
Regarding the `RegionalExtension` unions: GCC issues a lot of warnings regarding these empty unions. Maybe we can add a dummy field to each empty union via our asn1c patch mechanism.
I would be more than happy to add your MSVC instructions to the documentation! Also building Windows static libraries through GitHub actions would be great so we don't silently introduce any incompatibilities.

**Comment by riebl** [comment] 2023-03-12 18:12
For future reference: The dummy field `_placeholder` has been added to empty `RegionalExtension` unions. See the *regional_extension_unions.patch* file for details.

**Closed** 2023-08-17 13:06 UTC
